openapi: 3.0.1
info:
  title: Catálogo de Dados Abertos de Instituições Financeiras
  description: |
    Esta especificação define o formato da lista dos conjuntos de Dados Abertos a serem disponibilizados pelas IF, conforme definido pelo Banco Central do Brasil, assim como dados de contato e algumas informações básicas sobre cada conjunto.

    # Introdução
    O Banco Central passou a definir que certas informações, classificadas como de interesse público, passem a ser disponibilizadas em formatos abertos e padronizados. Cada conjunto de informação tem sua própria especificação, e serão listados no Catálogo de Dados Abertos.
    
    Um dos objetivos na iniciativa de dados abertos para as instituições financeiras é que ela agregue valor à população, com o menor custo de observância possível para as IFs. Com isso em mente, as especificações geradas serão simples o bastante para que possam ser atendidas simplesmente com a disponibilização de arquivos nos portais das instituições.
    
    # Especificação OpenAPI
    Como forma de descrever uma estrutura de dados padronizada, utilizamos o padrão [OpenAPI](https://github.com/OAI/OpenAPI-Specification). Com ele podemos definir caminhos e [schemas](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schema-object) a serem retornados por esses caminhos.
    
    # Autenticação

    As informações disponibilizadas baseadas nesta especificação não devem possuir nenhum tipo de autenticação.
    

    <SecurityDefinitions />
  version: 0.1.2
  contact:
    email: "apiteam??@bcb.gov.br"
  license:
    name: "Open Database License (ODbL)"
    url: "http://opendefinition.org/licenses/odc-odbl/"
paths:
  /catalogo:
    get:
      operationId: buscarCatalogo
      description: "Retorna informações sobre a instituição e sobre os conjuntos de\
        \ dados publicados como Dados Abertos.\n\nAlgumas informações são opcionais"
      responses:
        200:
          description: Resposta bem sucedida
          content:
            'application/json:':
              schema:
                $ref: '#/components/schemas/catalogo'
components:
  schemas:
    catalogo:
      type: object
      title: Catálogo de conjuntos de dados abertos
      description: Catálogo com informações dos conjuntos de dados abertos publicados pela instituição financeira.
      required:
        - cnpj
        - nome
        - dataUltimaAtualizacao
        - contatoArea
        - contatoEmail
        - conjuntos
      properties:
        cnpj:
          type: string
          title: CNPJ
          description: 'codigo CNPJ de 8 dígitos, formatado.'
          example: 01.010.101
          pattern: '^[0-9]{2}.[0-9]{3}.[0-9]{3}$'
        nome:
          type: string
          title: Nome da IF
          description: Nome da Instituição Financeira.
          example: Banco Xyz
          maxLength: 50
        dataUltimaAtualizacao:
          type: string
          format: date
          title: Data da última atualização
          description: 'Data da última atualização destas informações, no formato yyyy-mm-dd.'
          example: '2019-06-11'
        contatoArea:
          type: string
          title: Área de contato
          description: Nome da área de contato para tratar problemas nos dados.
          example: Ouvidoria
          maxLength: 50
        contatoEmail:
          type: string
          format: email
          title: E-mail de contato
          description: E-mail da área de contato para tratar problemas nos dados.
          example: ouvid@bancoxyz.com.br
        conjuntos:
          type: array
          title: Conjuntos de dados
          description: Lista de conjuntos de dados disponibilizados.
          items:
            title: Item do catálogo
            type: object
            description: Cada conjunto de dado faz referência a uma especificação implementada e indica onde ela está disponibilizada.
            required:
              - ref
              - nome
              - urlBase
              - urlVisualizacao
              - situacao
              - recursos
            properties:
              ref:
                type: string
                format: uri
                title: Referência à especificação da API 
                description: Endereço html da especificação OpenAPI no site do Banco Central
                example: 'https://www.bcb.gov.br/dadosabertos/apis/pilar3/1.0.0/especificacao'
                maxLength: 150
              nome:
                type: string
                title: Nome da API
                description: Nome da API, conforme definido na especificação.
                example: Basiléia - PillarIII
                maxLength: 100
              urlBase:
                type: string
                format: uri
                title: URL de base
                description: Indica o caminho base da implementação da API na IF.
                example: 'http://dadosabertos.bancoxyz.com.br/pillar/1.0/'
              urlVisualizacao:
                type: string
                format: uri
                title: URL de visualização
                description: Url que aponta para visualização dos dados no site da instituição.
                example: 'https://bancoxyz.com.br/ConsultaPillarIII'
              situacao:
                type: string
                title: Situação da implementação
                description: Indica o estado do desenvolvimento da API. Somente APIs marcadas como em 'Produção' são consideradas como publicadas.
                enum:
                  - Desenvolvimento
                  - Homologação
                  - Produção
                  - Descontinuada
                example: Produção
                maxLength: 20
              recursos:
                type: array
                title: Lista de recursos publicados
                description: Lista com os recursos implementados e publicados pela instituição
                items:
                  type: object
                  title: Recurso da API
                  description: Recurso implementado pela IF.
                  required:
                    - caminhoRecurso
                  properties:
                    caminhoRecurso:
                      type: string
                      format: uri
                      title: Caminho do recurso
                      description: Identificação do recurso implementado, conforme definido na especificação
                      example: '/KM1/{semestre}'
                      maxLength: 100
                    paramRecurso:
                      type: string
                      title: Nome do parâmetro 
                      description: Nome do parâmetro existente no recurso, conforme definido na especificação
                      example: 'semestre'
                      maxLength: 30
                    paramDisponiveis:
                      oneOf:
                        - type: array
                          title: Lista de parâmetros implementados
                          description: Lista com os parâmetros implementados pela instituição e que geram recursos válidos, conforme definido na especificação
                          items:
                            type: string
                            title: Parâmetro válido publicado
                            description: Parâmetro que gere recurso válido, conforme definido na especificação.
                            example: '201901'
                            maxLength: 50
                        - type: string
                          format: uri
                          title: URL de parâmetros  implementação
                          description: URL de definição da instituição, que retorna lista com os parâmetros implementadospela instituição e que geram recursos válidos, conforme definido na especificação
                          example: '/KM1/PeriodosDisponiveis'
                          maxLength: 100
              contatoArea:
                type: string
                title: Área de Contato API
                description: Nome da área de contato para tratar problemas nos dados específicos deste conjunto de dados. Este valor é opcional e deve ser preenchido se existir um contato de negócios específico para este conjunto.
                example: Financeiro
                maxLength: 50
              contatoEmail:
                type: string
                format: email
                title: E-mail de contato API
                description: E-mail da área de contato para tratar problemas nos dados específicos deste conjunto de dados. Este valor é opcional e deve ser preenchido se existir um contato de negócios específico para este conjunto.
                example: pillarIII@bancoxyz.com

