openapi: 3.0.1
info:
  title: Catálogo de Dados Abertos de Instituições Financeiras
  description: |
    Lista conjuntos de informação disponibilizados pelas IF como Dados Abertos
  version: 0.1.1
  contact:
    email: "apiteam??@bcb.gov.br"
  license:
    name: "Open Database License (ODbL)"
    url: "http://opendefinition.org/licenses/odc-odbl/"
servers:
  - url: 'http://editor.swagger.io/'
    description: Servidor de testes
paths:
  /catalogo:
    get:
      operationId: buscarCatalogo
      description: "Retorna informações sobre a instituição e sobre os conjuntos de\
        \ dados publicados como Dados Abertos.\n\nAlgumas informações são opcionais"
      responses:
        200:
          description: Resposta bem sucedida
          content:
            'application/json:':
              schema:
                $ref: '#/components/schemas/catalogo'
components:
  schemas:
    catalogo:
      type: object
      title: Catálogo de conjuntos de dados abertos
      description: Catálogo com informações dos conjuntos de dados abertos publicados pela instituição financeira.
      required:
        - codigo
        - nome
        - dataUltimaAtualizacao
        - contatoArea
        - contatoEmail
        - conjuntos
      properties:
        codigo:
          oneOf:
            - type: string
              title: CNPJ
              description: 'codigo CNPJ de 8 dígitos, formatado.'
              example: 01.010.101
              pattern: '^[0-9]{2}.[0-9]{3}.[0-9]{3}$'
            - type: string
              title: Código do Conglomerado Prudencial ou da instituição
              description: Identificação do Conglomerado Prudencial ou Instituição.
              example: A0000000
              pattern: '^[A-Z]{1}[0-9]{7}$'        nome:
          type: string
          title: Nome da IF
          description: Nome da Instituição Financeira.
          example: Banco Xyz
          maxLength: 50
          pattern: ^(.*)$
        dataUltimaAtualizacao:
          type: string
          format: date
          title: Data da última atualização
          description: 'Data da última atualização destas informações, no formato yyyy-mm-dd.'
          example: '2019-06-11'
        contatoArea:
          type: string
          title: Área de Contato
          description: Nome da área de contato para tratar problemas nos dados.
          example: Ouvidoria
          maxLength: 50
          pattern: ^(.*)$
        contatoEmail:
          type: string
          format: email
          title: E-mail de contato
          description: E-mail da área de contato para tratar problemas nos dados.
          example: ouvid@bancoxyz.com.br
        conjuntos:
          type: array
          title: Conjuntos de dados
          description: Lista de conjuntos de dados disponibilizados.
          items:
            title: Item do catálogo - API
            type: object
            description: Cada conjunto de dado faz referência a uma API publicada e indica onde ela está disponibilizada.
            required:
              - id
              - versao
              - urlBase
              - urlVisualizacao
              - situacao
              - recursos
            properties:
              ref:
                type: string
                format: uri
                title: Link para especificação da API
                description: Referência para especificação da API no site do Banco Central
                example: 'https://www.bcb.gov.br/dadosabertos/apis/pilar3/1.0.0/especificacao'
                maxLength: 150
              nome:
                type: string
                title: Nome da API
                description: Nome da API, conforme definido na especificação.
                example: Basiléia - PillarIII
                maxLength: 200
                pattern: ^(.*)$
              urlBase:
                type: string
                format: uri
                title: URL de base
                description: Indica o caminho base da implementação da API na IF.
                example: 'http://dadosabertos.bancoxyz.com.br/pillar/1.0/'
              urlVisualizacao:
                type: string
                format: uri
                title: URL de visualização
                description: Url que aponta para visualização dos dados no site da instituição.
                example: 'https://bancoxyz.com.br/ConsultaPillarIII'
              situacao:
                type: string
                title: Situação da API
                description: Indica o estado do desenvolvimento da API. Somente APIs marcadas como em 'Produção' são consideradas como publicadas.
                enum:
                  - Desenvolvimento
                  - Homologação
                  - Produção
                  - Descontinuada
                example: Produção
                maxLength: 20
                pattern: ^(.*)$
              recursos:
                type: array
                title: Lista de recursos da API
                description: Lista com os recursos implementados e publicados pela instituição
                items:
                  type: object
                  title: Recurso da API
                  description: Recurso implementado pela IF.
                  required:
                    - idRecurso
                  properties:
                    caminhoRecurso:
                      type: string
                      format: uri
                      title: URI template do recurso
                      description: URI de template para acesso ao recurso, conforme API.
                      example: '/KM1/{periodo}'
                      maxLength: 100
                    periodos:
                      oneOf:
                        - type: array
                          title: Lista de períodos com publicação
                          description: Para recursos com períodos definidos na norma, indica períodos com informação disponível.
                          items:
                            type: string
                            title: Período publicado
                            description: Período publicado, conforme norma definida.
                            example: '201901'
                            maxLength: 50
                            pattern: ^(.*)$
                        - type: string
                          format: uri
                          title: URL Períodos Disponíveis
                          description: URL opcional para buscar array de períodos disponíveis.
                          example: '/KM1/Periodos'
                          maxLength: 100
                    periodicidade:
                      type: string
                      title: Periodicidade
                      description: Informativo. Se houver periodicidade definida, indica qual é.
                      example: semestral
                      maxLength: 50
                      pattern: ^(.*)$
              contatoArea:
                type: string
                title: Área de Contato API
                description: Nome da área de contato para tratar problemas nos dados específicos desta API. Opcional
                example: Financeiro
                maxLength: 50
                pattern: ^(.*)$
              contatoEmail:
                type: string
                format: email
                title: E-mail de contato API
                description: E-mail da área de contato para tratar problemas nos dados desta API.
                example: pillarIII@bancoxyz.com

