openapi: 3.0.1
info:
  title: Taxas de Câmbio nos Cartões de Crédito
  version: 1.0.0
  description: |
    Esta especificação define a API de serviços que permite visualizar as taxas de câmbio diárias para o dólar utilizadas nos cartões de crédito de uso internacional:
  contact:
    email: "apiteam??@bcb.gov.br"
  license:
    name: "Open Database License (ODbL)"
    url: "http://opendefinition.org/licenses/odc-odbl/"
tags:
- name: API
  description: Informações sobre recursos disponíveis na API
paths:
  /itens:
    get:
      tags: [API]
      summary: Taxas de câmbio aplicadas nos cartões de
        crédito
      responses:
        200:
          description: Sucesso
          content:
            'application/json:':
              schema:
                $ref: '#/components/schemas/historicoTaxasCartoes'
              examples:
                Exemplo com vários cartoes e bandeiras e datas-base:
                  $ref: '#/components/examples/example1'  
                Exemplo com vários cartoes e bandeiras e a última data-base:
                  $ref:  '#/components/examples/example2'
      x-code-samples:
        - lang: 'Curl'
          source: |		
            curl -X GET "https://www.bancoxyz.com.br/dadosabertos/taxasCambioCartoesCredito/itens" -H "accept: application/json:"		
        - lang: 'Javascript - Node'
          source: |
            var request = require("request");

            var options = {
              method: 'GET',
              url: 'https://www.bancoxyz.com.br/dadosabertos/taxasCambioCartoesCredito/itens',
              headers: 
              {   'cache-control': 'no-cache'
              } 
            };
            request(options, function (error, response, body) {
              if (error) throw new Error(error);
              console.log(body);
            });		

        - lang: 'Javascript - Ajax'
          source: |
            var settings = {
              "async": true,
              "crossDomain": true,
              "url": "https://www.bancoxyz.com.br/dadosabertos/taxasCambioCartoesCredito/itens",
              "method": "GET",
              "headers": {
                "content-type": "application/json",
                "cache-control": "no-cache"
              }
            }

            $.ajax(settings).done(function (response) {
              console.log(response);
            });
        - lang: 'Python'
          source: |
            import requests
            url = "https://www.bancoxyz.com.br/dadosabertos/taxasCambioCartoesCredito/itens"
            headers = {
              'content-type': "application/json",
              'cache-control': "no-cache"
              }
            response = requests.request("GET", url, headers=headers)
            print(response.text)
        - lang: 'Java'
          source: |
            HttpResponse response = Unirest.get("https://www.bancoxyz.com.br/dadosabertos/taxasCambioCartoesCredito/itens")
            .header("cache-control", "no-cache")
            .asString();    
  /itens/ultimo:
    get:
      tags: [API]
      summary: Taxas de câmbio aplicadas nos cartões de
        crédito no último dia disponível
      responses:
        200:
          description: Sucesso
          content:
            'application/json:':
              schema:
                $ref: '#/components/schemas/historicoTaxasCartoes'
              examples:
                Exemplo com vários cartoes e bandeiras e a última data-base:
                  $ref:  '#/components/examples/example2'
      x-code-samples:
        - lang: 'Curl'
          source: |		
            curl -X GET "https://www.bancoxyz.com.br/dadosabertos/taxasCambioCartoesCredito/itens/ultimo" -H "accept: application/json:"		
        - lang: 'Javascript - Node'
          source: |
            var request = require("request");

            var options = {
              method: 'GET',
              url: 'https://www.bancoxyz.com.br/dadosabertos/taxasCambioCartoesCredito/itens/ultimo',
              headers: 
              {   'cache-control': 'no-cache'
              } 
            };
            request(options, function (error, response, body) {
              if (error) throw new Error(error);
              console.log(body);
            });		

        - lang: 'Javascript - Ajax'
          source: |
            var settings = {
              "async": true,
              "crossDomain": true,
              "url": "https://www.bancoxyz.com.br/dadosabertos/taxasCambioCartoesCredito/itens/ultimo",
              "method": "GET",
              "headers": {
                "content-type": "application/json",
                "cache-control": "no-cache"
              }
            }

            $.ajax(settings).done(function (response) {
              console.log(response);
            });
        - lang: 'Python'
          source: |
            import requests
            url = "https://www.bancoxyz.com.br/dadosabertos/taxasCambioCartoesCredito/itens/ultimo"
            headers = {
              'content-type': "application/json",
              'cache-control': "no-cache"
              }
            response = requests.request("GET", url, headers=headers)
            print(response.text)
        - lang: 'Java'
          source: |
            HttpResponse response = Unirest.get("https://www.bancoxyz.com.br/dadosabertos/taxasCambioCartoesCredito/itens/ultimo")
            .header("cache-control", "no-cache")
            .asString();    
components:
  schemas:
    historicoTaxasCartoes:
      type: array
      title: Lista de Cartões e seus Históricos de Taxas
      description: "Informações sobre a taxa de conversão do dólar dos Estados Unidos para reais referente aos gastos em moeda estrangeira de cartões de uso internacional"
      items:
        type: object
        title: Cartão e seus Históricos de Taxas
        description: Agrega os dados de um cartão de uma bandeira
        required:
          - cartaoNome
          - cartaoBandeira
          - historicoTaxas
        properties:
          cartaoNome:
            type: string
            title: Nome do Cartão
            description: "Nome do cartão de uso internacional"
            example: XYZ Paladium
            maxLength: 50
          cartaoBandeira:
            type: string
            title: Bandeira do Cartão
            description: "Nome do instituidor do arranjo de pagamento (bandeira do cartão)"
            example: Visa / Mastercard / Elo / American Express / ...
            maxLength: 50
          historicoTaxas:
            type: array
            title: Histórico de Taxas
            description: "Informações sobre a taxa de conversão do dólar dos Estados Unidos para reais referente aos gastos em moeda estrangeira do cartao de uso internacional."
            items:
              type: object
              required:
                - taxaTipoGasto
                - taxaData
                - taxaConversao
                - taxaDivulgacaoDataHora
              properties:
                taxaTipoGasto:
                  type: string
                  title: Tipo do Gasto
                  description: "Identificação do tipo de gasto efetuado: \n- Compras ou saques na função crédito\n- Compras ou saques na função débito à conta"
                  enum:
                    - Crédito
                    - Débito à conta
                  example:   Crédito
                  maxLength: 50
                taxaData:
                  type: string
                  format: date
                  title: Data
                  description: Data da taxa de conversão do dólar dos Estados Unidos para reais referente aos gastos em moeda estrangeira do cartao de uso internacional
                  example: '01/03/2020'
                taxaConversao:
                  title: Taxa de Conversão
                  type: number
                  format: double
                  multipleOf: 0.0001
                  example: 3.456789
                  description: "Taxa de conversão do dólar dos Estados Unidos para reais referente aos gastos em moeda estrangeira do cartao de uso internacional, representada com a precisão de até seis casas decimais"
                taxaDivulgacaoDataHora:
                  type: string
                  format: date-time
                  title: Data da Divulgação
                  description: "Data e hora da divulgação da  taxa de conversão do dólar dos Estados Unidos para reais referente aos gastos em moeda estrangeira do cartao de uso internacional"
                  example: '2017-07-21T17:32:28Z'
                  maxLength: 25
  examples:
    example1:
      value:
      - cartaoNome: XYZ Paladium
        cartaoBandeira: Visa 
        historicoTaxas:
          - taxaTipoGasto: Crédito
            taxaData: '2019-03-01'
            taxaConversao: 3.456789
            taxaDivulgacaoDataHora: '2019-03-02T17:32:28Z'
      - cartaoNome: XYZ Paladium
        cartaoBandeira: Elo 
        historicoTaxas:
          - taxaTipoGasto: Crédito
            taxaData: '2019-03-01'
            taxaConversao: 3.43322
            taxaDivulgacaoDataHora: '2019-03-02T17:32:28Z'
      - cartaoNome: XYZ Zirconium
        cartaoBandeira: Mastercard
        historicoTaxas:
          - taxaTipoGasto: Crédito
            taxaData: '2019-03-01'
            taxaConversao: 3.443
            taxaDivulgacaoDataHora: '2019-03-02T17:32:28Z'
      - cartaoNome: XYZ Zirconium
        cartaoBandeira: Mastercard
        historicoTaxas:
          - taxaTipoGasto: Crédito
            taxaData: '2019-03-01'
            taxaConversao: 3.4534
            taxaDivulgacaoDataHora: '2019-03-02T17:32:28Z'
      - cartaoNome: XYZ Paladium
        cartaoBandeira: Visa 
        historicoTaxas:
          - taxaTipoGasto: Crédito
            taxaData: '2019-03-02'
            taxaConversao: 3.84342
            taxaDivulgacaoDataHora: '2019-03-03T17:32:28Z'
      - cartaoNome: XYZ Zirconium
        cartaoBandeira: Mastercard
        historicoTaxas:
          - taxaTipoGasto: Crédito
            taxaData: '2019-03-02'
            taxaConversao: 3.465433
            taxaDivulgacaoDataHora: '2019-03-03T17:32:28Z'
    example2:
      value:
      - cartaoNome: XYZ Paladium
        cartaoBandeira: Visa 
        historicoTaxas:
          - taxaTipoGasto: Crédito
            taxaData: '2019-03-02'
            taxaConversao: 3.456789
            taxaDivulgacaoDataHora: '2019-03-02T17:32:28Z'
      - cartaoNome: XYZ Zirconium
        cartaoBandeira: Mastercard
        historicoTaxas:
          - taxaTipoGasto: Crédito
            taxaData: '2019-03-02'
            taxaConversao: 3.443
            taxaDivulgacaoDataHora: '2019-03-02T17:32:28Z'
      - cartaoNome: XYZ Paladium
        cartaoBandeira: Elo 
        historicoTaxas:
          - taxaTipoGasto: Crédito
            taxaData: '2019-03-02'
            taxaConversao: 3.43322
            taxaDivulgacaoDataHora: '2019-03-02T17:32:28Z'
      - cartaoNome: XYZ Zirconium
        cartaoBandeira: Mastercard
        historicoTaxas:
          - taxaTipoGasto: Crédito
            taxaData: '2019-03-02'
            taxaConversao: 3.4534
            taxaDivulgacaoDataHora: '2019-03-02T17:32:28Z'

          
